package Kanta.test;
// Generated by ComTest BEGIN
import Kanta.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.25 14:27:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmTarkistusTest {



  // Generated by ComTest BEGIN
  /** testTarkista24 */
  @Test
  public void testTarkista24() {    // PvmTarkistus: 24
    PvmTarkistus pvm = new PvmTarkistus(); 
    assertEquals("From: PvmTarkistus line: 27", "Päivämäärä on liian lyhyt", pvm.tarkista("12121")); 
    assertEquals("From: PvmTarkistus line: 28", "Ei ole oikea päivämäärä", pvm.tarkista("k")); 
    assertEquals("From: PvmTarkistus line: 29", "Päivämäärä on liian pitkä", pvm.tarkista("12.000000.00")); 
    assertEquals("From: PvmTarkistus line: 30", "Liian pieni päivämäärä", pvm.tarkista("0.12.2023")); 
    assertEquals("From: PvmTarkistus line: 31", "Liian pieni kuukausi", pvm.tarkista("1.0.23")); 
    assertEquals("From: PvmTarkistus line: 32", "Liian pieni vuosi", pvm.tarkista("12.3.0")); 
    assertEquals("From: PvmTarkistus line: 33", null, pvm.tarkista("23.4.2023")); 
    assertEquals("From: PvmTarkistus line: 34", null, pvm.tarkista("23.4.22")); 
  } // Generated by ComTest END
}