package Kayttaja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kayttaja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.24 11:10:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class cardioTreenitTest {



  // Generated by ComTest BEGIN
  /** 
   * testPoista284 
   * @throws SailoException when error
   */
  @Test
  public void testPoista284() throws SailoException {    // cardioTreenit: 284
    cardioTreenit cardiot = new cardioTreenit(); 
    cardioTreeni juoksu1 = new cardioTreeni(), juoksu2 = new cardioTreeni(), juoksu3 = new cardioTreeni(); 
    juoksu1.rekisteroi(); juoksu2.rekisteroi(); juoksu3.rekisteroi(); 
    int id1 = juoksu1.getTunnusNro(); 
    cardiot.lisaa(juoksu1); cardiot.lisaa(juoksu2); cardiot.lisaa(juoksu3); 
    assertEquals("From: cardioTreenit line: 291", 1, cardiot.poista(id1+1)); 
    assertEquals("From: cardioTreenit line: 292", null, cardiot.poista(id1+1)); assertEquals("From: cardioTreenit line: 292", 2, cardiot.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaId310 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaId310() throws SailoException {    // cardioTreenit: 310
    cardioTreenit cardiot = new cardioTreenit(); 
    cardioTreeni juoksu1 = new cardioTreeni(), juoksu2 = new cardioTreeni(), juoksu3 = new cardioTreeni(); 
    juoksu1.rekisteroi(); juoksu2.rekisteroi(); juoksu3.rekisteroi(); 
    int id1 = juoksu1.getTunnusNro(); 
    cardiot.lisaa(juoksu1); cardiot.lisaa(juoksu2); cardiot.lisaa(juoksu3); 
    assertEquals("From: cardioTreenit line: 317", true, cardiot.annaId(id1  ) == juoksu1); 
    assertEquals("From: cardioTreenit line: 318", true, cardiot.annaId(id1+1) == juoksu2); 
    assertEquals("From: cardioTreenit line: 319", true, cardiot.annaId(id1+2) == juoksu3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId334 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId334() throws SailoException {    // cardioTreenit: 334
    cardioTreenit cardiot = new cardioTreenit(); 
    cardioTreeni juoksu1 = new cardioTreeni(), juoksu2 = new cardioTreeni(), juoksu3 = new cardioTreeni(); 
    juoksu1.rekisteroi(); juoksu2.rekisteroi(); juoksu3.rekisteroi(); 
    int id1 = juoksu1.getTunnusNro(); 
    cardiot.lisaa(juoksu1); cardiot.lisaa(juoksu2); cardiot.lisaa(juoksu3); 
    assertEquals("From: cardioTreenit line: 341", 1, cardiot.etsiId(id1+1)); 
    assertEquals("From: cardioTreenit line: 342", 2, cardiot.etsiId(id1+2)); 
  } // Generated by ComTest END
}