package Kayttaja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kayttaja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.14 14:18:08 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikeTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi74 */
  @Test
  public void testRekisteroi74() {    // Liike: 74
    Liike liike1 = new Liike(); 
    assertEquals("From: Liike line: 76", 0, liike1.getTunnusNro()); 
    liike1.rekisteroi(); 
    Liike liike2 = new Liike(); 
    liike2.rekisteroi(); 
    int n1 = liike1.getTunnusNro(); 
    int n2 = liike2.getTunnusNro(); 
    assertEquals("From: Liike line: 82", n2-1, n1); 
  } // Generated by ComTest END
}