package Kayttaja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kayttaja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.24 12:09:35 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreenitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa51 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa51() throws SailoException {    // Treenit: 51
    Treenit treenit = new Treenit(); 
    SaliTreeni selka = new SaliTreeni(), jalka = new SaliTreeni(); 
    assertEquals("From: Treenit line: 55", 0, treenit.getLkm()); 
    treenit.lisaa(selka); assertEquals("From: Treenit line: 56", 1, treenit.getLkm()); 
    treenit.lisaa(jalka); assertEquals("From: Treenit line: 57", 2, treenit.getLkm()); 
    treenit.lisaa(selka); assertEquals("From: Treenit line: 58", 3, treenit.getLkm()); 
    assertEquals("From: Treenit line: 59", selka, treenit.anna(0)); 
    assertEquals("From: Treenit line: 60", jalka, treenit.anna(1)); 
    assertEquals("From: Treenit line: 61", jalka, treenit.anna(2)); 
    assertEquals("From: Treenit line: 62", false, treenit.anna(1) == selka); 
    assertEquals("From: Treenit line: 63", true, treenit.anna(1) == jalka); 
    try {
    assertEquals("From: Treenit line: 64", selka, treenit.anna(3)); 
    fail("Treenit: 64 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    treenit.lisaa(selka); assertEquals("From: Treenit line: 65", 4, treenit.getLkm()); 
    treenit.lisaa(selka); assertEquals("From: Treenit line: 66", 5, treenit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista96 
   * @throws SailoException when error
   */
  @Test
  public void testPoista96() throws SailoException {    // Treenit: 96
    Treenit treenit = new Treenit(); 
    SaliTreeni mave1 = new SaliTreeni(), mave2 = new SaliTreeni(), mave3 = new SaliTreeni(); 
    mave1.rekisteroi(); mave2.rekisteroi(); mave3.rekisteroi(); 
    int id1 = mave1.getTunnusNro(); 
    treenit.lisaa(mave1); treenit.lisaa(mave2); treenit.lisaa(mave3); 
    assertEquals("From: Treenit line: 103", 1, treenit.poista(id1+1)); 
    assertEquals("From: Treenit line: 104", null, treenit.poista(id1+1)); assertEquals("From: Treenit line: 104", 2, treenit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi302 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi302() throws SailoException {    // Treenit: 302
    Treenit treenit = new Treenit(); 
    SaliTreeni jalka1 = new SaliTreeni(); jalka1.parse("1|jalkapäivä|23.2.2023|hyväfiilis|"); 
    SaliTreeni  jalka2 = new SaliTreeni (); jalka2.parse("2|kyykkypäivä|24.3.2023|ihan ok|"); 
    SaliTreeni  jalka3 = new SaliTreeni (); jalka3.parse("3|pohjepäivä|25.3.2023|hyvä"); 
    SaliTreeni jalka4 = new SaliTreeni (); jalka4.parse("4|takareisipäivä|26.3.2023|"); 
    SaliTreeni  jalka5 = new SaliTreeni (); jalka5.parse("5|jalkapäivä|23.4.2023|huono"); 
    treenit.lisaa(jalka1); treenit.lisaa(jalka2); treenit.lisaa(jalka3); treenit.lisaa(jalka4); treenit.lisaa(jalka5); 
  } // Generated by ComTest END
}